### ISSUE TITLE
Upcoming Events page should show further in advance

### ISSUE THREAD

**Issue by cnitz18** [salonisaraf/CS506-bookstore-loyalty#15]
The Upcoming Events page is not flexible at all, and should at least give the user the option to see further in advance, rather than just the current date's events. I see in the Requirements and Specs that you intended to only show the current date on this page, but nonetheless I think it would add to the user experience to be able to switch which date we are looking at, at the very least. Ideally, I think it would be nice to have the option to pull up a monthly calendar somehow and select any date to zoom in on, but even just allowing the user to switch between dates immediately before or immediately after today would be good. 

Severity: Enhancement

**Comment by sophiasheen** [comment]
Thank you for the suggestion. The reason that the Events page is only showing the day's view was due to our client's request. The Bookstore specifically asked us to limit the Events to the current day because they do not wish to reveal future events ahead of time. Thus we only give our user access to the current day and do not allow for changing dates on the Events page.

**Comment by liblit** [comment]
I’d like to point out that this is a perfect illustration of the distinction between clients and users. @cnitz18 represents the *users*: UW Bookstore customers who would like to know about upcoming events. But as @sophiasheen points out, the *client* (UW Bookstore) has business reasons to deny that request.

There is no easy fix when clients and users disagree. But it is worth recognizing that this is what is going on here, just as your wise professor taught you can happen. :man_teacher:

**Comment by cnitz18** [comment]
I understand. If the bookstore doesn’t want to change the functionality at all, then maybe change the page title to “Today’s Events” instead? Just to avoid confusion/frustration on the user end
