### ISSUE TITLE
Login page has lost password link, but there's no password field

### ISSUE THREAD

**Issue by kassssc** [salonisaraf/CS506-bookstore-loyalty#7]
The login page provides us with a "lost password" link to reset or recover our password, but there is no password involved in the login process, it is simply the student ID and e-mail. This is a little bit confusing. Would that link recover your ID?

Severity: Moderate, this could confuse users. The website should be more explicit about what a user could use to log-in.

**Comment by salonisaraf** [comment]
Our team also noticed this issue during the HCI lecture series and work session held from April 17 -19 and we have now resolved this issue in the redesigned version of our app. We appreciate your feedback!
